src/main/java/com/nexmo/client/HttpWrapper.java, src/main/java/com/nexmo/client/auth/AuthMethod.java, src/main/java/com/nexmo/client/auth/JWTAuthMethod.java, src/main/java/com/nexmo/client/auth/TokenAuthMethod.java, src/main/java/com/nexmo/client/voice/SendDTMFMethod.java, src/main/java/com/nexmo/client/voice/StartTalkMethod.java, src/main/java/com/nexmo/client/voice/StopTalkMethod.java, src/main/java/com/nexmo/client/voice/endpoints/AbstractMethod.java, src/main/java/com/nexmo/client/voice/endpoints/CreateCallMethod.java, src/main/java/com/nexmo/client/voice/endpoints/ListCallsMethod.java, src/main/java/com/nexmo/client/voice/endpoints/ModifyCallMethod.java, src/main/java/com/nexmo/client/voice/endpoints/ReadCallMethod.java, src/main/java/com/nexmo/client/voice/endpoints/StartStreamMethod.java, src/main/java/com/nexmo/client/voice/endpoints/StopStreamMethod.java, src/test/java/com/nexmo/client/auth/JWTAuthMethodTest.java, src/test/java/com/nexmo/client/voice/NexmoVoiceClientTest.java, src/test/java/com/nexmo/client/voice/SendDTMFMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/AbstractMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/CreateCallMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/ListCallsMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/ModifyCallMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/ReadCallMethodTest.java
Needed to replace `HttpUriRequest` with `RequestBuilder` in AbstractMethod because other auth methods need to change things other than just headers (and HttpUriRequest is almost immutable).
=> Abstract method interface change

README.md
* Existing import statement for `NexmoClient` was incorrect.
* Missing import statement for `CallEvent`
To reduce the chances of this happening I'd recommend creating a quickstart repository and ensure examples are copied/pasted from code examples that compile.
=> Fix import statements so example will compile

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, src/main/java/com/nexmo/client/insight/CallerType.java, src/main/java/com/nexmo/client/insight/InsightClient.java, src/main/java/com/nexmo/client/insight/advanced/AdvancedInsightEndpoint.java, src/main/java/com/nexmo/client/insight/advanced/AdvancedInsightRequest.java, src/main/java/com/nexmo/client/insight/advanced/AdvancedInsightResponse.java, src/main/java/com/nexmo/client/insight/basic/BasicInsightRequest.java, src/main/java/com/nexmo/client/insight/standard/StandardInsightEndpoint.java, src/main/java/com/nexmo/client/insight/standard/StandardInsightRequest.java, src/main/java/com/nexmo/client/insight/standard/StandardInsightResponse.java, src/test/java/com/nexmo/client/insight/InsightClientTest.java, src/test/java/com/nexmo/client/insight/advanced/AdvancedInsightEndpointTest.java, src/test/java/com/nexmo/client/insight/advanced/AdvancedInsightRequestTest.java, src/test/java/com/nexmo/client/insight/advanced/AdvancedInsightResponseTest.java, src/test/java/com/nexmo/client/insight/standard/StandardInsightEndpointTest.java, src/test/java/com/nexmo/client/insight/standard/StandardInsightRequestTest.java, src/test/java/com/nexmo/client/insight/standard/StandardInsightResponseTest.java
Added the new `cnam` parameter for Standard and Advanced Insight requests, along with the necessary additions to the response objects.
=> Implement cnam parameter for Number Insight

CHANGELOG.md, src/main/java/com/nexmo/client/voice/endpoints/AbstractMethod.java, src/test/java/com/nexmo/client/sms/SendMessageEndpointTest.java, src/test/java/com/nexmo/client/voice/endpoints/CallTest.java
A bug in HttpClient <=4.4 means that charset is ignored for the entities added to PUT and POST requests.
This fix intercepts the `HttpRequest` created by `RequestBuilder.build()`, and manually sets the Entity with a UTF-8 encoded version, if a `UrlEncodedFormEntity` is found.
An alternative approach would have been to upgrade HttpClient to 4.5+ and change all the calls to `RequestBuilder.post(url)` (and other methods) to `RequestBuilder.post().setUri(uri)` everywhere in the code (because of a different bug that still exists in 4.5+).
This PR addresses #60
=> A fix for SMS requests being made using ISO-8859-1 instead of UTF-8

CHANGELOG.md, src/main/java/com/nexmo/client/voice/Call.java, src/test/java/com/nexmo/client/voice/endpoints/CallTest.java
Fixes #63
Treat `eventUrl` as an array, not as a String
=> Send Event Url as a list

CHANGELOG.md, src/main/java/com/nexmo/client/sms/messages/Message.java, src/test/java/com/nexmo/client/sms/SendMessageEndpointTest.java
There was a missing setter for the statusReportRequired property, reported in #71. This PR adds it in.
=> Add setter for statusReportRequired. Resolves #71

.bumpversion.cfg, CHANGELOG.md, README.md, build.gradle, src/main/java/com/nexmo/client/HttpWrapper.java, src/main/java/com/nexmo/client/voice/endpoints/ModifyCallMethod.java, src/test/java/com/nexmo/client/voice/endpoints/ModifyCallMethodTest.java
The API currently returns 204 responses, resulting in a NullPointerException. This PR fixes that, and results in `null` being returned from the relevant calls.
=> Modify call - support 204

CHANGELOG.md, src/main/java/com/nexmo/client/sms/messages/Message.java
Remove the length restriction on the `from` parameter of the `Message` class.
=> Remove fifteen digit client verification

CHANGELOG.md, src/main/java/com/nexmo/client/voice/ncco/RecordNcco.java, src/main/java/com/nexmo/client/voice/ncco/SplitRecording.java, src/test/java/com/nexmo/client/voice/ncco/RecordNccoTest.java
Add the option to enable `split` recording to the `RecordNcco` object.  This can be enabled via the following:
```java
RecordNcco ncco = new RecordNcco();
ncco.setSplit(SplitRecording.CONVERSATION);
```
=> Add split recording to the RecordNcco object.

CHANGELOG.md, src/main/java/com/nexmo/client/voice/ncco/ConversationNcco.java, src/test/java/com/nexmo/client/voice/ncco/ConversationNccoTest.java
Update the `ConversationNcco` so that it correctly serializes the `musicOnHoldUrl` property into an array.  This is a temporary fix to serialization in order to maintain backwards compatibility.
See: #166 for initiative to clean up objects entirely.
Resolves: #164
=> Update conversation musicOnHoldUrl to Array

CHANGELOG.md, README.md, src/main/java/com/nexmo/client/account/AccountClient.java, src/main/java/com/nexmo/client/account/Country.java, src/main/java/com/nexmo/client/account/Network.java, src/main/java/com/nexmo/client/account/PrefixPricingEndpoint.java, src/main/java/com/nexmo/client/account/PrefixPricingMethod.java, src/main/java/com/nexmo/client/account/PrefixPricingRequest.java, src/main/java/com/nexmo/client/account/PrefixPricingResponse.java, src/main/java/com/nexmo/client/account/PricingEndpoint.java, src/main/java/com/nexmo/client/account/PricingMethod.java, src/main/java/com/nexmo/client/account/PricingRequest.java, src/main/java/com/nexmo/client/account/PricingResponse.java, src/main/java/com/nexmo/client/account/ServiceType.java, src/main/java/com/nexmo/client/account/SmsPricingMethod.java, src/main/java/com/nexmo/client/account/VoicePricingMethod.java, src/test/java/com/nexmo/client/ClientTest.java, src/test/java/com/nexmo/client/account/AccountClientTest.java, src/test/java/com/nexmo/client/verify/VerifyClientCheckEndpointTest.java, src/test/java/com/nexmo/client/verify/VerifyClientSearchEndpointTest.java, src/test/java/com/nexmo/client/verify/VerifyClientVerifyControlEndpointTest.java, src/test/java/com/nexmo/client/verify/VerifyClientVerifyEndpointTest.java
Add the ability to query the API for voice and SMS pricing via the `getVoicePrice` and `getSmsPrice` methods on the `AccountClient`.
Resolves #88 and #87.
=> Implement Voice and SMS pricing on AccountClient

.travis.yml, build.gradle
As of June 18, Maven Central requires TLSv1.2. Both the `oraclejdk7` and `openjdk7` distributions in Travis CI are too old to support TLSv1.2.
I have modified our `build.gradle` file to fallback to HTTP for retrieving dependencies when building in a Java 7 environment.
See: https://central.sonatype.org/articles/2018/May/04/discontinue-support-for-tlsv11-and-below/
=> Fix Travis CI Java 7 Build

CHANGELOG.md, README.md, src/main/java/com/nexmo/client/NexmoClient.java, src/main/java/com/nexmo/client/conversion/ConversionClient.java, src/main/java/com/nexmo/client/conversion/ConversionEndpoint.java, src/main/java/com/nexmo/client/conversion/ConversionMethod.java, src/main/java/com/nexmo/client/conversion/ConversionRequest.java, src/test/java/com/nexmo/client/conversion/ConversionClientTest.java, src/test/java/com/nexmo/client/conversion/ConversionMethodTest.java
Added the ability to interact with the [Conversion API](https://developer.nexmo.com/messaging/conversion-api/overview).
This was done in a similar fashion to the other APIs with an `Endpoint`, `Method`, and `Client`.  Interaction with the API can be done through `getConversionClient()` on the `NexmoClient`.
=> Add access to the Conversion API

CHANGELOG.md, src/main/java/com/nexmo/client/sms/SmsClient.java, src/main/java/com/nexmo/client/sms/SmsSingleSearchEndpoint.java, src/main/java/com/nexmo/client/sms/SmsSingleSearchResponse.java, src/test/java/com/nexmo/client/sms/SmsClientTest.java
Added endpoint to search messages by single id. `getSms` on the `SmsClient`.
Not super happy with this implementation and would like to revisit it for next major version release.
=> Add getSms to SmsClient

CHANGELOG.md, README.md, src/main/java/com/nexmo/client/NexmoClient.java, src/main/java/com/nexmo/client/auth/AbstractAuthMethod.java, src/main/java/com/nexmo/client/auth/AuthMethod.java, src/main/java/com/nexmo/client/auth/TokenAuthMethod.java, src/main/java/com/nexmo/client/redact/RedactClient.java, src/main/java/com/nexmo/client/redact/RedactEndpoint.java, src/main/java/com/nexmo/client/redact/RedactMethod.java, src/main/java/com/nexmo/client/redact/RedactRequest.java, src/main/java/com/nexmo/client/redact/RedactResponse.java, src/main/java/com/nexmo/client/voice/endpoints/AbstractMethod.java, src/test/java/com/nexmo/client/redact/RedactClientTest.java, src/test/java/com/nexmo/client/redact/RedactMethodTest.java, src/test/java/com/nexmo/client/redact/RedactRequestTest.java
Added `RedactClient` to support the [Redact API](https://developer.nexmo.com/api/redact). This API works a bit differently so here's some things of note/concern:
Authentication is done through basic authentication parameters. I added a method to the `AuthMethod` interface called `applyAsBasicAuth`. This method is implemented to throw an `UnsupportedOperationException`. It was done this way because `AbstractMethod` uses `AuthMethod` in its logic and needed visibility of both `apply` and `applyAsBasicAuth`.
Additionally, a method was added to `AbstractMethod` called `isUseBasicAuth` which defaults to `false`. This allows extending classes to instruct `AbstractMethod` to use basic authentication parameters when constructing the request instead of standard request parameters.
The POST body of …
=> Add Support for Redact API

CHANGELOG.md, src/main/java/com/nexmo/client/incoming/CallDirection.java, src/main/java/com/nexmo/client/incoming/CallEvent.java, src/main/java/com/nexmo/client/incoming/CallStatus.java, src/main/java/com/nexmo/client/incoming/InputEvent.java, src/main/java/com/nexmo/client/incoming/MessageEvent.java, src/main/java/com/nexmo/client/incoming/MessageType.java, src/main/java/com/nexmo/client/incoming/RecordEvent.java, src/test/java/com/nexmo/client/incoming/CallDirectionTest.java, src/test/java/com/nexmo/client/incoming/CallEventTest.java, src/test/java/com/nexmo/client/incoming/CallStatusTest.java, src/test/java/com/nexmo/client/incoming/InputEventTest.java, src/test/java/com/nexmo/client/incoming/MessageEventTest.java, src/test/java/com/nexmo/client/incoming/MessageTypeTest.java, src/test/java/com/nexmo/client/incoming/RecordEventTest.java
This change adds objects for deserializing the following events:
- `com.nexmo.client.incoming.MessageEvent` for incoming SMS.
- `com.nexmo.client.incoming.CallEvent` for information sent to the `event_url`.
- `com.nexmo.client.incoming.InputEvent` for dtmf input events.
- `com.nexmo.client.incoming.RecordEvent` for recording call information events.
=> Add Data Objects for Various Events

CHANGELOG.md, src/main/java/com/nexmo/client/insight/RoamingDetails.java, src/main/java/com/nexmo/client/insight/advanced/AdvancedInsightResponse.java, src/main/java/com/nexmo/client/voice/CallDirection.java, src/main/java/com/nexmo/client/voice/CallStatus.java, src/main/java/com/nexmo/client/voice/MachineDetection.java, src/main/java/com/nexmo/client/voice/ModifyCallAction.java, src/main/java/com/nexmo/client/voice/VoiceName.java, src/main/java/com/nexmo/client/voice/ncco/RecordingFormat.java, src/test/java/com/nexmo/client/insight/advanced/AdvancedInsightResponseTest.java, src/test/java/com/nexmo/client/voice/MachineDetectionTest.java, src/test/java/com/nexmo/client/voice/ModifyCallActionTest.java, src/test/java/com/nexmo/client/voice/VoiceNameTest.java, src/test/java/com/nexmo/client/voice/endpoints/CallInfoTest.java, src/test/java/com/nexmo/client/voice/ncco/RecordingFormatTest.java
Enums that are used for deserialization of JSON should fallback to a default `UNKNOWN` value instead of throwing an `IllegalArgumentException`. This allows for graceful failing in instances where the API and the library are out of sync with available values.
- `null` cannot be used in a switch statement when switching over enumerations without getting an NPE.
- Returning `null` could mean more work on the utilization side in regards to avoid NPEs. The idea here is to fail gracefully.
- This is a good application of the [Null Object Pattern](https://en.wikipedia.org/wiki/Null_object_pattern#Java)
Resolves #186
=> Add fallback values to enums

CHANGELOG.md, src/main/java/com/nexmo/client/voice/VoiceName.java, src/test/java/com/nexmo/client/voice/VoiceNameTest.java
Adds another field to the `VoiceName` enum to explicitly set the display name. This helps to avoid some ambiguity in attempting to programatically set the voice name.
Also adds a method called `getDisplayName` to the enum in order to avoid the reliance on `toString` which should not be used for this purpose.
=> Explicitly Define Voice Name Display Values in VoiceName Enumeration

CHANGELOG.md, src/main/java/com/nexmo/client/HttpConfig.java, src/test/java/com/nexmo/client/applications/endpoints/CreateApplicationMethodTest.java, src/test/java/com/nexmo/client/applications/endpoints/DeleteApplicationMethodTest.java, src/test/java/com/nexmo/client/applications/endpoints/GetApplicationEndpointTest.java, src/test/java/com/nexmo/client/applications/endpoints/ListApplicationsEndpointTest.java, src/test/java/com/nexmo/client/applications/endpoints/UpdateApplicationMethodTest.java, src/test/java/com/nexmo/client/redact/RedactMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/CreateCallMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/ListCallsMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/ReadCallMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/StartStreamMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/StartTalkMethodTest.java, src/test/java/com/nexmo/client/voice/endpoints/StopStreamMethodTest.java
When rewriting base uri we should still append the version string, ie `/v1`.
=> Always Apply Version String to Base URI

CHANGELOG.md, src/main/java/com/nexmo/client/AbstractMethod.java, src/test/java/com/nexmo/client/AbstractMethodTest.java
Update `AbstractMethod` to make sure that JSON `StringEntity` are sent using UTF-8 as this is what the server expects.
Resolves #227
=> Make sure that the entity is sent using UTF-8.

CHANGELOG.md, src/main/java/com/nexmo/client/applications/ApplicationType.java, src/main/java/com/nexmo/client/applications/UpdateApplicationMethod.java, src/main/java/com/nexmo/client/applications/UpdateApplicationRequest.java, src/main/java/com/nexmo/client/auth/AbstractAuthMethod.java, src/main/java/com/nexmo/client/auth/TokenAuthMethod.java, src/test/java/com/nexmo/client/applications/UpdateApplicationMethodTest.java, src/test/java/com/nexmo/client/auth/TokenAuthMethodTest.java
Update application (v1) was not functioning correctly because the endpoint was expecting a json body. It also expected api key and secret parameters to be added to the json body.
I updated the `UpdateApplicationMethod` to switch to using a json payload as a fix before application v2 can be implemented. I also added the ability for `TokenAuthMethod` to attach api credentials to a json entity.
=> Fix Update Application

.bumpversion.cfg, CHANGELOG.md, README.md, build.gradle, src/main/java/com/nexmo/client/AbstractMethod.java, src/main/java/com/nexmo/client/HttpWrapper.java, src/main/java/com/nexmo/client/applications/UpdateApplicationMethod.java, src/main/java/com/nexmo/client/auth/TokenAuthMethod.java, src/main/java/com/nexmo/client/voice/CreateCallMethod.java, src/main/java/com/nexmo/client/voice/ModifyCallMethod.java, src/main/java/com/nexmo/client/voice/SendDtmfMethod.java, src/main/java/com/nexmo/client/voice/StartStreamMethod.java, src/main/java/com/nexmo/client/voice/StartTalkMethod.java, src/test/java/com/nexmo/client/AbstractMethodTest.java, src/test/java/com/nexmo/client/auth/TokenAuthMethodTest.java
Previously there was a fix in the `AbstractMethod` that would de-encode and re-encode a `StringEntity` into `UTF-8`. However, this doesn't work as it was intended.
This fix changes all of the `StringEntity` instantiations to supply a `ContentType.APPLICATION_JSON` which will force the default Charset to use `UTF-8`
=> Fix UTF-8 Encoding

CHANGELOG.md, build.gradle, src/main/java/com/nexmo/client/NexmoClient.java, src/main/java/com/nexmo/client/auth/JWTAuthMethod.java, src/test/java/com/nexmo/client/NexmoClientTest.java, src/test/java/com/nexmo/client/auth/JWTAuthMethodTest.java
Instead of relying on Auth0, this PR changes the Server SDK to use the [Nexmo JWT Library](https://github.com/nexmo/nexmo-jwt-jdk).
=> Migrate from Auth0 JWT to Nexmo JWT

src/main/java/com/vonage/client/logging/LoggingUtils.java, src/test/java/com/vonage/client/LoggingUtilTest.java
_Problem: Logging an empty response was throwing IllegalArgumentException from EntityUtils
Solution: For an empty response log nothing by adding a Null check_
=> Fix: Error from no-content responses

CHANGELOG.md, src/main/java/com/vonage/client/application/CreateApplicationMethod.java, src/main/java/com/vonage/client/application/DeleteApplicationMethod.java, src/main/java/com/vonage/client/application/GetApplicationMethod.java, src/main/java/com/vonage/client/application/ListApplicationsMethod.java, src/main/java/com/vonage/client/application/UpdateApplicationMethod.java, src/test/java/com/vonage/client/application/AppBasicAuthTest.java, src/test/java/com/vonage/client/application/CreateApplicationMethodTest.java, src/test/java/com/vonage/client/application/DeleteApplicationMethodTest.java, src/test/java/com/vonage/client/application/GetApplicationMethodTest.java, src/test/java/com/vonage/client/application/ListApplicationsMethodTest.java, src/test/java/com/vonage/client/application/UpdateApplicationMethodTest.java
Changed create application request auth to use basic auth based on changes announced by the Product API team
> As part of releasing an internal security update for the Applications Service, we noticed that v2 of the public-facing Application API was accepting API key/secret as request params for authentication. This has been treated as a bug.
Request parameter auth was never intended to be supported and was not documented publicly or internally for v2 of the API. We recommend customers use header auth (basic auth) for this API instead. https://developer.nexmo.com/concepts/guides/authentication#header-based-api-key-and-secret-authentication
=> changed create application request auth

CHANGELOG.md, src/main/java/com/vonage/client/insight/RoamingDeseriazlizer.java, src/main/java/com/vonage/client/insight/RoamingDetails.java, src/test/java/com/vonage/client/insight/AdvancedInsightResponseTest.java
Parallel update for the Java SDK to coincide with the dotnet SDKs update for the top-level parsing for the Advanced Number Insights Roaming object, also added a couple of tests to validate that we can handle a null Ported/Reachable satus
=> number insight parsing update

CHANGELOG.md, src/main/java/com/vonage/client/auth/RequestSigning.java
.NET brain made me forget that `==` operator works on referecnes and not literals in java
=> switchign from == to .equals for string comparison for contentType

.github/workflows/build.yml, .github/workflows/publish.yml, CONTRIBUTORS.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/vonage/client/AbstractMethod.java, src/test/java/com/vonage/client/AbstractMethodTest.java, src/test/java/com/vonage/client/ClientTest.java, src/test/java/com/vonage/client/LoggingUtilTest.java, src/test/java/com/vonage/client/TestUtils.java, src/test/java/com/vonage/client/VonageClientTest.java, src/test/java/com/vonage/client/numbers/NumbersClientTest.java, src/test/java/com/vonage/client/sms/SmsClientTest.java, src/test/java/com/vonage/client/sns/SnsClientTest.java, src/test/java/com/vonage/client/voice/VoiceClientTest.java
[Link to ticket](https://jira.vonage.com/browse/DEVX-6070)
Currently, the project's tests fail to pass with JDK >= 17 due to outdated libraries using illegal reflective access; support for which was removed and after JDK 16 it is not possible to allow this. This PR updates the Gradle build with the latest version of dependent libraries (which addresses some security vulnerabilities) and removes dependency on PowerMock; instead using Mockito 4.4 for static mocks (which is the only feature of PowerMock that was being used).
The tests now pass on JDK 18.
=> [DEVX-6070] Update project to work with JDK 18

.github/workflows/build.yml, README.md, build.gradle
This PR changes references to the 6.x branch to `main` so that in the future this won't be needed
=> Renamed 6.x to main

src/main/java/com/vonage/client/messages/MessageRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerAudioRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerFileRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerImageRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerTextRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerVideoRequest.java, src/main/java/com/vonage/client/messages/mms/MmsAudioRequest.java, src/main/java/com/vonage/client/messages/mms/MmsImageRequest.java, src/main/java/com/vonage/client/messages/mms/MmsRequest.java, src/main/java/com/vonage/client/messages/mms/MmsVcardRequest.java, src/main/java/com/vonage/client/messages/mms/MmsVideoRequest.java, src/main/java/com/vonage/client/messages/sms/SmsTextRequest.java, src/main/java/com/vonage/client/messages/viber/ViberImageRequest.java, src/main/java/com/vonage/client/messages/viber/ViberRequest.java, src/main/java/com/vonage/client/messages/viber/ViberTextRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappAudioRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappCustomRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappFileRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappImageRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappTemplateRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappTextRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappVideoRequest.java, src/test/java/com/vonage/client/messages/MessageRequestTest.java
This PR moves the Channel and Message type in the Messages implementation to be constructor parameters in MessageRequests, which is more appropriate and simpler than having builders override an abstract method to set it, since it's immutable by design.
=> Move Channel and MessageType to Request constructor

src/main/java/com/vonage/client/messages/MessageRequest.java, src/main/java/com/vonage/client/messages/mms/MmsRequest.java, src/main/java/com/vonage/client/messages/sms/SmsTextRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappRequest.java, src/test/java/com/vonage/client/messages/MessageRequestTest.java
This PR allows any string to be used for the sender field by default in `MessageRequest`, since the [API spec ](https://developer.vonage.com/api/messages-olympus) does not strictly prohibit non-E164 numbers to be used as the `from` field in SMS and MMS requests.
=> Be more permissive with SMS and MMS senders

build.gradle, src/main/java/com/vonage/client/auth/VonageUnacceptableAuthException.java, src/main/java/com/vonage/client/numbers/SearchNumbersFilter.java, src/main/java/com/vonage/client/voice/PhoneEndpoint.java, src/main/java/com/vonage/client/voice/Recording.java, src/test/java/com/vonage/client/AbstractMethodTest.java
The dependencies on Apache Commons libraries is not necessary and can easily be replaced by standard JDK libraries.
=> Remove Apache Commons dependencies

src/main/java/com/vonage/client/AbstractMethod.java, src/main/java/com/vonage/client/HttpWrapper.java, src/test/java/com/vonage/client/AbstractMethodTest.java
This PR is a "just in case" fix for the User-Agent potentially not being set in requests, including a test for it. It also ensures the UTF-8 charset is used, since it appears to be an unresolved bug in `org.apache.http.client.methods.RequestBuilder` constructors.
=> Ensure User-Agent is set in all request headers and UTF-8 encoding is used

README.md, src/main/java/com/vonage/client/VonageClient.java, src/main/java/com/vonage/client/redact/RedactClient.java, src/main/java/com/vonage/client/redact/RedactRequest.java
The [Redact API](https://developer.vonage.com/api/redact) was never GA's (or even enter Beta stage). This PR deprecates it for clarity, with the aim of removing it in a future release.
=> Deprecate Redact client

src/main/java/com/vonage/client/messages/whatsapp/Template.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappTemplateRequest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappTemplateRequestTest.java
This PR makes the `parameters` field in `WhatsappTemplateRequest` more permissive.
=> Allow any object in WhatsappTemplate parameters list

CHANGELOG.md, build.gradle, src/main/java/com/vonage/client/auth/JWTAuthMethod.java, src/main/java/com/vonage/client/verify/BaseRequest.java, src/main/java/com/vonage/client/verify/BaseResult.java, src/main/java/com/vonage/client/verify/CheckEndpoint.java, src/main/java/com/vonage/client/verify/ControlEndpoint.java, src/main/java/com/vonage/client/verify/ControlResponse.java, src/main/java/com/vonage/client/verify/Psd2Endpoint.java, src/main/java/com/vonage/client/verify/Psd2Request.java, src/main/java/com/vonage/client/verify/SearchEndpoint.java, src/main/java/com/vonage/client/verify/SearchVerifyResponseDeserializer.java, src/main/java/com/vonage/client/verify/VerifyDetails.java, src/main/java/com/vonage/client/verify/VerifyEndpoint.java, src/main/java/com/vonage/client/verify/VerifyStatusDeserializer.java
This PR updates the dependency on [nexmo-jwt-jdk](https://github.com/Nexmo/nexmo-jwt-jdk) to use [vonage-jwt-jdk](https://github.com/Vonage/vonage-jwt-jdk).
=> Use Vonage JWT library

CHANGELOG.md, src/main/java/com/vonage/client/messages/messenger/MessengerAudioRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerFileRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerImageRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerTextRequest.java, src/main/java/com/vonage/client/messages/messenger/MessengerVideoRequest.java, src/main/java/com/vonage/client/messages/sms/SmsTextRequest.java, src/main/java/com/vonage/client/messages/viber/ViberImageRequest.java, src/main/java/com/vonage/client/messages/viber/ViberRequest.java, src/main/java/com/vonage/client/messages/viber/ViberTextRequest.java, src/main/java/com/vonage/client/messages/whatsapp/Locale.java, src/main/java/com/vonage/client/messages/whatsapp/Template.java, src/main/java/com/vonage/client/messages/whatsapp/Whatsapp.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappAudioRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappCustomRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappFileRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappImageRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappTemplateRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappTextRequest.java, src/main/java/com/vonage/client/messages/whatsapp/WhatsappVideoRequest.java, src/test/java/com/vonage/client/messages/MessagesClientTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappAudioRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappCustomRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappFileRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappImageRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappTemplateRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappTextRequestTest.java, src/test/java/com/vonage/client/messages/whatsapp/WhatsappVideoRequestTest.java
This PR fixes some inaccuracies / inconsistencies in `WhatsappTemplateRequest`. Namely, it changes `parameters` to be a `List<String>` instead of `List<?>`, makes `policy` optional and adds enumerations for supported locales. It also restricts the sender field to numbers.
=> Fix WhatsappTemplate

src/main/java/com/vonage/client/messages/MessageResponseException.java, src/main/java/com/vonage/client/messages/SendMessageEndpoint.java, src/test/java/com/vonage/client/messages/SendMessageEndpointTest.java
This PR fixes parsing error responses from the Messages v1 API ([as reported on the Community Slack](https://vonage-community.slack.com/archives/C9H152ATW/p1660931679229029)) where the response doesn't contain JSON body, leading to `VonageUnexpectedException` being thrown as the response is attempted to be parsed into the `MessageResponseException` object.
=> Fix parsing MessageResponseException with no body

src/main/java/com/vonage/client/video/CreateSessionEndpoint.java, src/main/java/com/vonage/client/video/CreateSessionResponse.java, src/test/java/com/vonage/client/video/CreateSessionResponseTest.java, src/test/java/com/vonage/client/video/VideoClientTest.java
[The endpoint for creating video sessions returns a response wrapped in an array](https://developer.vonage.com/api/video#session-create). This PR fixes the parsing failing due to expecting a non-wrapped JSON response instead.
=> Fix CreateSessionResponse parsing

.bumpversion.cfg, .github/workflows/publish.yml, README.md, build.gradle
Given [the current deficiency in GitHub Packages](https://github.com/orgs/community/discussions/26634), releasing preview versions to GitHub Packages instead of Maven Central is unsuitable. This PR reverts the change made in #419. It also fixes the bump2version configuration, which currently does not support non-final release versions, making beta versioning impossible. It disables tagging to fix the issue where duplicate tags are pushed after a release.
=> Don't use GitHub Packages & fix bumpversion.cfg

.github/workflows/publish.yml, README.md, build.gradle
This PR uses the [Gradle Nexus Publish plugin](https://github.com/gradle-nexus/publish-plugin/) to simplify releasing to Maven Central, by not requiring manual login to the Nexus repository manager web interface to perform the release.
=> Automate release to Maven Central

.github/workflows/publish.yml, CHANGELOG.md, bumpversion.sh
This is a workaround for the branch protection rules not working as intended, where the NexmoDev user can't bypass PR requirements when creating a release. Instead, version bumping will be performed manually, along with changelog updates. This then necessitates a review prior to creating a release, which is probably a good thing.
=> Manually invoke bump2version

CHANGELOG.md, README.md, src/main/java/com/vonage/client/VonageClient.java, src/main/java/com/vonage/client/auth/JWTAuthMethod.java, src/main/java/com/vonage/client/video/Role.java, src/main/java/com/vonage/client/video/TokenOptions.java, src/main/java/com/vonage/client/video/VideoClient.java, src/test/java/com/vonage/client/video/TokenOptionsTest.java, src/test/java/com/vonage/client/video/VideoClientTest.java
This PR adds the missing token generation capabilities to the SDK, which is required for the Video integration. Users call the `VideoClient#generateToken(String, TokenOptions)` method to get a new signed JWT for a given session with the desired options.
Implementation-wise, this piggybacks on the `JWTAuthMethod`, which uses the [`com.vonage:jwt` library](https://github.com/Vonage/vonage-jwt-jdk).
=> Add client token generation for Video API

src/main/java/com/vonage/client/video/DeleteArchiveEndpoint.java, src/main/java/com/vonage/client/video/ForceDisconnectEndpoint.java, src/main/java/com/vonage/client/video/MuteSessionEndpoint.java, src/main/java/com/vonage/client/video/MuteStreamEndpoint.java, src/main/java/com/vonage/client/video/PatchArchiveStreamEndpoint.java, src/main/java/com/vonage/client/video/ProjectDetails.java, src/main/java/com/vonage/client/video/Role.java, src/main/java/com/vonage/client/video/SetArchiveLayoutEndpoint.java, src/main/java/com/vonage/client/video/SetStreamLayoutEndpoint.java, src/main/java/com/vonage/client/video/SignalAllEndpoint.java, src/main/java/com/vonage/client/video/SignalEndpoint.java, src/main/java/com/vonage/client/video/SignalRequest.java, src/main/java/com/vonage/client/video/TokenOptions.java, src/main/java/com/vonage/client/video/VideoClient.java, src/test/java/com/vonage/client/ClientTest.java, src/test/java/com/vonage/client/TestUtils.java, src/test/java/com/vonage/client/video/TokenOptionsTest.java, src/test/java/com/vonage/client/video/VideoClientTest.java
- Adds the required `scope` claim to the JWT
- Improves testing of `VideoClient#generateToken`
- Fixes mishandling of empty 2xx responses
- MuteSession and MuteStream return nothing (API spec was mis-specified)
- Note: API specs are wrong about `signal`, `signallAll` and `forceDisconnect`: they return 204 not 200.
=> [VIDEO] Fix token generation & endpoints
