src/com/nexmo/insight/sdk/examples/InsightNumber.java
src/com/nexmo/verify/sdk/examples/CheckNumber.java
src/com/nexmo/verify/sdk/examples/SearchVerify.java
src/com/nexmo/verify/sdk/examples/VerifyNumber.java

I saw Java 1.6 compatibility was removed so I restored it (Tim and I agreed on that on a previous email conversation). If you don't need it, just exclude that commit and take only the examples.

Number insight and verify examples

---

src/com/nexmo/messaging/sdk/NexmoSmsClient.java

which will allow users of this client to plugin their custom HttpClient.

Exposing a HttpClient setter for NexmoSmsClient 

---

src/examples/java/com/nexmo/sns/sdk/examples/SubscribeAndPublishExample.java
src/main/java/com/nexmo/client/voice/Call.java
src/main/java/com/nexmo/client/voice/CallEndpoint.java
src/main/java/com/nexmo/client/voice/CallRecord.java
src/main/java/com/nexmo/client/voice/ncco/ConnectNcco.java
src/main/java/com/nexmo/security/RequestSigning.java
src/test/java/com/nexmo/client/voice/endpoints/CallEndpointTest.java
src/test/java/com/nexmo/client/voice/endpoints/CallRecordTest.java
src/test/java/com/nexmo/client/voice/endpoints/CallTest.java
src/test/java/com/nexmo/client/voice/endpoints/CreateCallMethodTest.java
src/test/java/com/nexmo/client/voice/endpoints/ListCallsMethodTest.java
src/test/java/com/nexmo/client/voice/endpoints/ReadCallMethodTest.java
src/test/java/com/nexmo/client/voice/ncco/ConnectNccoTest.java

Removed a few TODO comments, and fixed a few more.
Significant changes were:
* Rename `Endpoint` to `CallEndpoint`
* Throw a `NexmoUnexpectedException` from `RequestSigning.verifyRequestSignature`

Removing/fixing TODO comments.

---

build.gradle
src/examples/java/com/nexmo/client/examples/com/nexmo/client/voice/servlet/examples/TestNccoServlet.java
src/examples/java/com/nexmo/client/voice/servlet/examples/TestNccoServlet.java
src/main/java/com/nexmo/client/voice/servlet/AbstractAnswerServlet.java
src/main/java/com/nexmo/client/voice/servlet/NccoResponse.java
src/main/java/com/nexmo/client/voice/servlet/NccoResponseBuilder.java
src/main/webapp/WEB-INF/web.xml
src/test/java/com/nexmo/client/voice/servlet/AbstractAnswerServletTest.java

Adds a servlet for implementing Ncco webhooks.

Ncco servlet

---

README.md

- Modify a call
- Send DTMF to a call
- Start and stop a stream to a call
- Start and stop a talk message to a call

Add more code samples to the README

---

src/main/java/com/nexmo/client/voice/DtmfPayload.java
src/main/java/com/nexmo/client/voice/DtmfRequest.java
src/main/java/com/nexmo/client/voice/DtmfResponse.java
src/main/java/com/nexmo/client/voice/ModifyCallResponse.java
src/main/java/com/nexmo/client/voice/StreamPayload.java
src/main/java/com/nexmo/client/voice/StreamRequest.java
src/main/java/com/nexmo/client/voice/StreamResponse.java
src/main/java/com/nexmo/client/voice/TalkPayload.java
src/main/java/com/nexmo/client/voice/TalkRequest.java
src/main/java/com/nexmo/client/voice/TalkResponse.java
src/main/java/com/nexmo/client/voice/VoiceName.java

@judy2k can you give me some feedback on these?

Add some javadoc comments to DTMF, Stream, and Talk objects

---

.gitignore
build.gradle

Changes to build.gradle to enable upload to Maven Central.

Maven packaging

---

README.md

Been getting questions about installation with Maven and use without a dependency manager, so I've added some instructions, including general advice to use *something*.

Add instructions for Maven and manual Java users.

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

- use CallInfo class in README example
- fix typo in PR template

use CallInfo class in README example

---

src/main/java/com/nexmo/client/insight/InsightClient.java
src/main/java/com/nexmo/client/voice/endpoints/AbstractMethod.java

Work done based on discoveries writing Quickstart code.

Quickstart fixes

---

build.gradle

Added a 'depJar' task that builds a fat jar file.

---

README.md
build.gradle

Following the [release process](https://github.com/Nexmo/nexmo-java/wiki/Releasing-nexmo-java)

Update version number to 2.0.0

---

CHANGELOG.md
README.md

Updates to README and CHANGELOG.

Releasing 2.0.2

---

src/main/java/com/nexmo/client/voice/CallStatus.java

com.fasterxml.jackson.databind.JsonMappingException on CANCELLED calls #69

bugfix com.fasterxml.jackson.databind.JsonMappingException on CANCELLED calls #69

---

src/main/java/com/nexmo/client/numbers/BuyNumberEndpoint.java
src/main/java/com/nexmo/client/numbers/BuyNumberRequest.java
src/main/java/com/nexmo/client/numbers/BuyNumberResponse.java
src/main/java/com/nexmo/client/numbers/ListNumbersResponse.java
src/main/java/com/nexmo/client/numbers/NumbersClient.java
src/main/java/com/nexmo/client/numbers/SearchNumbersResponse.java
src/test/java/com/nexmo/client/numbers/BuyNumberEndpointTest.java
src/test/java/com/nexmo/client/numbers/BuyNumberRequestAndResponseTest.java
src/test/java/com/nexmo/client/numbers/NumbersClientTest.java

Add the endpoint to purchase a number

---

CHANGELOG.md
src/main/java/com/nexmo/client/NexmoClient.java
src/main/java/com/nexmo/client/applications/ApplicationClient.java
src/main/java/com/nexmo/client/applications/ApplicationDetails.java
src/main/java/com/nexmo/client/applications/ApplicationKeys.java
src/main/java/com/nexmo/client/applications/ApplicationType.java
src/main/java/com/nexmo/client/applications/CreateApplicationRequest.java
src/main/java/com/nexmo/client/applications/ListApplicationsRequest.java
src/main/java/com/nexmo/client/applications/ListApplicationsResponse.java
src/main/java/com/nexmo/client/applications/UpdateApplicationRequest.java
src/main/java/com/nexmo/client/applications/VoiceApplicationDetails.java
src/main/java/com/nexmo/client/applications/WebHook.java
src/main/java/com/nexmo/client/applications/endpoints/ApplicationsEndpoint.java
src/main/java/com/nexmo/client/applications/endpoints/CreateApplicationMethod.java
src/main/java/com/nexmo/client/applications/endpoints/DeleteApplicationMethod.java
src/main/java/com/nexmo/client/applications/endpoints/EmbeddedApplicationDetails.java
src/main/java/com/nexmo/client/applications/endpoints/GetApplicationEndpoint.java
src/main/java/com/nexmo/client/applications/endpoints/ListApplicationsEndpoint.java
src/main/java/com/nexmo/client/applications/endpoints/UpdateApplicationMethod.java
src/test/java/com/nexmo/client/applications/ApplicationClientTest.java
src/test/java/com/nexmo/client/applications/ApplicationTypeTest.java
src/test/java/com/nexmo/client/applications/endpoints/ApplicationDetailsTest.java
src/test/java/com/nexmo/client/applications/endpoints/CreateApplicationMethodTest.java
src/test/java/com/nexmo/client/applications/endpoints/DeleteApplicationMethodTest.java
src/test/java/com/nexmo/client/applications/endpoints/GetApplicationEndpointTest.java
src/test/java/com/nexmo/client/applications/endpoints/ListApplicationsEndpointTest.java
src/test/java/com/nexmo/client/applications/endpoints/ListApplicationsResponseTest.java
src/test/java/com/nexmo/client/applications/endpoints/UpdateApplicationMethodTest.java

Add a client for applications and related functionality.

Applications Client

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/CallModifier.java
src/main/java/com/nexmo/client/voice/ModifyCallAction.java
src/main/java/com/nexmo/client/voice/ModifyCallResponse.java
src/main/java/com/nexmo/client/voice/TransferCallPayload.java
src/main/java/com/nexmo/client/voice/TransferDestination.java
src/main/java/com/nexmo/client/voice/VoiceClient.java
src/main/java/com/nexmo/client/voice/endpoints/CallsEndpoint.java
src/main/java/com/nexmo/client/voice/endpoints/ModifyCallMethod.java
src/test/java/com/nexmo/client/voice/CallModifierTest.java
src/test/java/com/nexmo/client/voice/TransferCallPayloadTest.java
src/test/java/com/nexmo/client/voice/VoiceClientTest.java
src/test/java/com/nexmo/client/voice/endpoints/ModifyCallMethodTest.java

Add the ability to transfer calls, earmuff, mute, etc.

Modify call extension

---

README.md
src/main/java/com/nexmo/client/NexmoClient.java

This was driven by a support issue where this feature was not documented.

Add short description of setHttpClient

---

CHANGELOG.md
build.gradle
src/main/java/com/nexmo/client/sms/RejectedMessage.java
src/main/java/com/nexmo/client/sms/SearchRejectedMessagesEndpoint.java
src/main/java/com/nexmo/client/sms/SearchRejectedMessagesRequest.java
src/main/java/com/nexmo/client/sms/SearchRejectedMessagesResponse.java
src/main/java/com/nexmo/client/sms/SearchSmsRequest.java
src/main/java/com/nexmo/client/sms/SearchSmsResponse.java
src/main/java/com/nexmo/client/sms/SmsClient.java
src/main/java/com/nexmo/client/sms/SmsDateSearchRequest.java
src/main/java/com/nexmo/client/sms/SmsDetails.java
src/main/java/com/nexmo/client/sms/SmsIdSearchRequest.java
src/main/java/com/nexmo/client/sms/SmsSearchEndpoint.java
src/test/java/com/nexmo/client/TestUtils.java
src/test/java/com/nexmo/client/sms/SearchRejectedMessagesEndpointTest.java
src/test/java/com/nexmo/client/sms/SearchRejectedMessagesResponseTest.java
src/test/java/com/nexmo/client/sms/SearchSmsEndpointTest.java
src/test/java/com/nexmo/client/sms/SearchSmsResponseTest.java
src/test/java/com/nexmo/client/sms/SmsClientTest.java

Add searchSMS and searchRejections.

Sms coverage

---

build.gradle
src/main/java/com/nexmo/client/auth/AuthCollection.java
src/main/java/com/nexmo/client/voice/Recording.java
src/main/java/com/nexmo/client/voice/VoiceClient.java
src/main/java/com/nexmo/client/voice/endpoints/DownloadRecordingEndpoint.java

Download a recording, automatically using JWT auth.

downloadRecording

---

CHANGELOG.md
src/main/java/com/nexmo/client/NexmoClient.java
src/main/java/com/nexmo/client/auth/AuthCollection.java
src/main/java/com/nexmo/client/auth/JWTAuthMethod.java
src/test/java/com/nexmo/client/NexmoClientTest.java

Expose basic JWT generation in NexmoClient.

Generate token

---

.bumpversion.cfg
CHANGELOG.md
README.md
build.gradle
src/main/java/com/nexmo/client/HttpWrapper.java
src/main/java/com/nexmo/client/verify/VerifyClient.java
src/main/java/com/nexmo/client/verify/VerifyRequest.java
src/main/java/com/nexmo/client/verify/endpoints/VerifyEndpoint.java
src/test/java/com/nexmo/client/verify/VerifyClientTest.java
src/test/java/com/nexmo/client/verify/endpoints/VerifyEndpointTest.java

VerifyRequest now supports all supported parameters.

Missing verify params

---

.bumpversion.cfg
CHANGELOG.md
README.md
build.gradle
src/main/java/com/nexmo/client/HttpWrapper.java

3.4.0 Release

---

.bumpversion.cfg
README.md
build.gradle
src/main/java/com/nexmo/client/HttpWrapper.java

3.4.1 Release

---

CHANGELOG.md
README.md
src/main/java/com/nexmo/client/account/AccountClient.java
src/main/java/com/nexmo/client/account/TopUpEndpoint.java
src/main/java/com/nexmo/client/account/TopUpMethod.java
src/main/java/com/nexmo/client/account/TopUpRequest.java
src/test/java/com/nexmo/client/account/AccountClientTest.java

Add the ability to top-up your auto-reloadable account. Method will return `true` if successful or throw an exception if unsuccessful.

Add Top-Up to the Account Client

---

.travis.yml
build.gradle

Add Travis CI JDK 9 environment. Resolves #157

Add jdk 9 testing

---

CHANGELOG.md
src/main/java/com/nexmo/client/HttpWrapper.java

The User Agent String will now also include the Java version.

Add Java version to user agent.

---

CHANGELOG.md
README.md
build.gradle
src/main/java/com/nexmo/client/account/AccountClient.java
src/main/java/com/nexmo/client/account/CreateSecretMethod.java
src/main/java/com/nexmo/client/account/CreateSecretRequest.java
src/main/java/com/nexmo/client/account/GetSecretMethod.java
src/main/java/com/nexmo/client/account/ListSecretsMethod.java
src/main/java/com/nexmo/client/account/ListSecretsResponse.java
src/main/java/com/nexmo/client/account/RevokeSecretMethod.java
src/main/java/com/nexmo/client/account/SecretManagementEndpoint.java
src/main/java/com/nexmo/client/account/SecretRequest.java
src/main/java/com/nexmo/client/account/SecretResponse.java
src/test/java/com/nexmo/client/account/AccountClientTest.java
src/test/java/com/nexmo/client/account/CreateSecretMethodTest.java
src/test/java/com/nexmo/client/account/GetSecretMethodTest.java
src/test/java/com/nexmo/client/account/ListSecretsMethodTest.java
src/test/java/com/nexmo/client/account/RevokeSecretMethodTest.java

Add support for the Secret Management API https://developer.nexmo.com/api/account/secret-management.

Implement Secret Management

---

CONTRIBUTORS.md
src/main/java/com/nexmo/client/auth/AuthCollection.java

Hello.
I do not think the ```com.nexmo.client.NexmoClientException``` is needed.
Because it is not used
what do you think?
Thanks.

Remove dead code

---

CHANGELOG.md
CONTRIBUTORS.md
src/main/java/com/nexmo/client/HttpWrapper.java

Add `useSystemProperties()` before `build()` in `HttpWrapper.createHttpClient()`.
Changelog deliberately not updated as it didn't seem like a notable enough change.

Fix issue #154

---

.gitignore
CONTRIBUTORS.md
README.md

Modify READ.ME file. Upgrade from `compile` to `implementation` on gradle dependencies

change compile to implementation gradle

---

LICENSE.txt

Bump year 2017 -> 2018 in the license file.

Bump year in the license

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/ncco/RecordNcco.java
src/test/java/com/nexmo/client/voice/ncco/RecordNccoTest.java

Add Channel Support to Record Action

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/CallOrder.java
src/main/java/com/nexmo/client/voice/CallsFilter.java
src/test/java/com/nexmo/client/voice/CallsFilterTest.java
src/test/java/com/nexmo/client/voice/ListCallsMethodTest.java
src/test/java/com/nexmo/client/voice/VoiceClientTest.java

Add calls filter builder

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/CallsFilter.java
src/main/java/com/nexmo/client/voice/ncco/ConnectAction.java
src/main/java/com/nexmo/client/voice/ncco/ConversationAction.java
src/main/java/com/nexmo/client/voice/ncco/InputAction.java
src/main/java/com/nexmo/client/voice/ncco/PhoneEndpoint.java
src/main/java/com/nexmo/client/voice/ncco/RecordAction.java
src/main/java/com/nexmo/client/voice/ncco/SipEndpoint.java
src/main/java/com/nexmo/client/voice/ncco/TalkAction.java
src/main/java/com/nexmo/client/voice/ncco/WebSocketEndpoint.java
src/test/java/com/nexmo/client/voice/CallsFilterTest.java
src/test/java/com/nexmo/client/voice/ncco/ConnectActionTest.java
src/test/java/com/nexmo/client/voice/ncco/ConversationActionTest.java
src/test/java/com/nexmo/client/voice/ncco/InputActionTest.java
src/test/java/com/nexmo/client/voice/ncco/PhoneEndpointTest.java
src/test/java/com/nexmo/client/voice/ncco/RecordActionTest.java
src/test/java/com/nexmo/client/voice/ncco/SipEndpointTest.java
src/test/java/com/nexmo/client/voice/ncco/TalkActionTest.java
src/test/java/com/nexmo/client/voice/ncco/WebSocketEndpointTest.java

Some QoL change for using the builders in the action classes.

Add Builder Static Methods

---

CHANGELOG.md
README.md
src/main/java/com/nexmo/client/HttpConfig.java
src/main/java/com/nexmo/client/NexmoClient.java
src/test/java/com/nexmo/client/HttpConfigTest.java
src/test/java/com/nexmo/client/NexmoClientTest.java

Add Static Builder Method to NexmoClient

---

CHANGELOG.md
README.md
src/main/java/com/nexmo/client/voice/Call.java
src/main/java/com/nexmo/client/voice/ncco/Ncco.java
src/test/java/com/nexmo/client/voice/CallTest.java
src/test/java/com/nexmo/client/voice/endpoints/CallTest.java

You can now call the `createCall` method using a `Call` object containing an `Ncco`.
Resolves #230

Create Call with NCCO

---

.travis.yml
build.gradle
src/main/java/com/nexmo/client/package-info.java
src/main/java/com/nexmo/client/verify/VerifyClient.java
src/main/java/com/nexmo/client/verify/VerifyRequest.java
src/main/java/com/nexmo/client/voice/CallsEndpoint.java
src/main/java/com/nexmo/client/voice/VoiceClient.java

JDK11 removed some features (like jaxb) and they need to be brought in as dependencies. I also enabled JDK 11 testing on Travis CI.

Add JDK 11 Support

---

CHANGELOG.md
CONTRIBUTORS.md
src/main/java/com/nexmo/client/redact/RedactRequest.java
src/test/java/com/nexmo/client/redact/RedactRequestTest.java

Sharif malik fix for message product in redact api

---

CHANGELOG.md
CONTRIBUTORS.md
src/main/java/com/nexmo/client/voice/VoiceName.java
src/test/java/com/nexmo/client/voice/VoiceNameTest.java

Just adding `MATTHEW` to the `VoiceName` enum so I can use it to create a `TalkAction` with the new voice. 
Please, by all means, add any more names if appropriate.

add MATTHEW/Matthew to VoiceName

---

CHANGELOG.md
src/main/java/com/nexmo/client/account/AccountClient.java
src/main/java/com/nexmo/client/account/SettingsEndpoint.java
src/main/java/com/nexmo/client/account/SettingsMethod.java
src/main/java/com/nexmo/client/account/SettingsRequest.java
src/main/java/com/nexmo/client/account/SettingsResponse.java
src/test/java/com/nexmo/client/account/AccountClientTest.java
src/test/java/com/nexmo/client/account/SettingsMethodTest.java

Add support for account settings: https://developer.nexmo.com/api/account#changeAccountSettings

Change Account Settings

---

CHANGELOG.md
src/main/java/com/nexmo/client/insight/AdvancedInsightEndpoint.java
src/main/java/com/nexmo/client/insight/AdvancedInsightRequest.java
src/test/java/com/nexmo/client/insight/AdvancedInsightEndpointTest.java
src/test/java/com/nexmo/client/insight/AdvancedInsightRequestTest.java
src/test/java/com/nexmo/client/insight/InsightClientTest.java

Add support for async advanced number insight.

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/ncco/PhoneEndpoint.java
src/test/java/com/nexmo/client/voice/ncco/PhoneEndpointTest.java

Add support for ringback in NCCO

---

CHANGELOG.md
src/main/java/com/nexmo/client/numbers/SearchNumbersFilter.java
src/main/java/com/nexmo/client/numbers/Type.java
src/main/java/com/nexmo/client/numbers/UpdateNumberRequest.java
src/test/java/com/nexmo/client/numbers/SearchNumbersEndpointTest.java
src/test/java/com/nexmo/client/numbers/TypeTest.java
src/test/java/com/nexmo/client/numbers/UpdateNumberEndpointTest.java

Add some of the missing number api functionality.

Add missing number functionality

---

CHANGELOG.md
src/main/java/com/nexmo/client/verify/VerifyMethod.java
src/main/java/com/nexmo/client/verify/VerifyRequest.java
src/test/java/com/nexmo/client/verify/VerifyMethodTest.java

Verification Workflow Support

---

CHANGELOG.md
src/main/java/com/nexmo/client/voice/CallModifier.java
src/main/java/com/nexmo/client/voice/TransferCallPayload.java
src/main/java/com/nexmo/client/voice/TransferDestination.java
src/main/java/com/nexmo/client/voice/VoiceClient.java
src/test/java/com/nexmo/client/voice/TransferCallPayloadTest.java
src/test/java/com/nexmo/client/voice/VoiceClientTest.java

Add inline transfer to NCCO support.

---

.bumpversion.cfg
CHANGELOG.md
CONTRIBUTORS.md
README.md
build.gradle
src/main/java/com/nexmo/client/HttpWrapper.java

bumping version: 5.1.0 -> 5.2.0

---

CODE_OF_CONDUCT.md
CONTRIBUTORS.md

added Code of Conduct file to repo

create CODE_OF_CONDUCT.md file

---

CHANGELOG.md

corrected change log for release 5.3.0-RELEASE

updated change log for v5.3.0 release

---

CHANGELOG.md
build.gradle
src/main/java/com/nexmo/client/AbstractMethod.java
src/main/java/com/nexmo/client/logging/LoggingUtils.java
src/test/java/com/nexmo/client/AbstractMethodTest.java
src/test/java/com/nexmo/client/ClientTest.java
src/test/java/com/nexmo/client/NexmoClientTest.java
src/test/java/com/nexmo/client/numbers/NumbersClientTest.java
src/test/java/com/nexmo/client/sms/SmsClientTest.java
src/test/java/com/nexmo/client/sns/SnsClientTest.java
src/test/java/com/nexmo/client/voice/VoiceClientTest.java

* Add ability to log api response when logging is in debug mode.
* Fix failing test due to logging response change.

Add Ability to log API response

---

CHANGELOG.md
src/main/java/com/nexmo/client/verify/BaseRequest.java
src/main/java/com/nexmo/client/verify/CheckMethod.java
src/main/java/com/nexmo/client/verify/ControlEndpoint.java
src/main/java/com/nexmo/client/verify/Psd2Endpoint.java
src/main/java/com/nexmo/client/verify/Psd2Method.java
src/main/java/com/nexmo/client/verify/Psd2Request.java
src/main/java/com/nexmo/client/verify/SearchMethod.java
src/main/java/com/nexmo/client/verify/VerifyClient.java
src/main/java/com/nexmo/client/verify/VerifyEndpoint.java
src/main/java/com/nexmo/client/verify/VerifyRequest.java
src/main/java/com/nexmo/client/verify/VerifyResponse.java
src/main/java/com/nexmo/client/voice/ncco/AppEndpoint.java
src/test/java/com/nexmo/client/verify/ControlEndpointTest.java
src/test/java/com/nexmo/client/verify/Psd2MethodTest.java
src/test/java/com/nexmo/client/verify/VerifyClientPsd2EndpointTest.java
src/test/java/com/nexmo/client/verify/VerifyClientVerifyEndpointTest.java
src/test/java/com/nexmo/client/verify/VerifyMethodTest.java

* Add PSD2 verification request
* Add test for PSD2 verification request
* Add PSD2 verification with Workflow
* Refactored PSD2 and 2FA verification requests to extend the optional fields from a base class
closes #296

[feat] Add PSD2 Verification

---

CONTRIBUTORS.md
src/main/java/com/vonage/client/auth/MD5Util.java
src/main/java/com/vonage/client/sms/HexUtil.java
src/main/java/com/vonage/client/sms/callback/AbstractMOServlet.java
src/main/java/com/vonage/client/sms/callback/messages/MO.java
src/main/java/com/vonage/client/sms/messages/Message.java
src/main/java/com/vonage/client/sms/messages/TextMessage.java
src/main/java/com/vonage/client/sms/messages/WapPushMessage.java
src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java
src/main/java/com/vonage/client/verify/BaseResult.java

src/main/java/com/vonage/client/auth/MD5Util.java
src/main/java/com/vonage/client/sms/HexUtil.java
src/main/java/com/vonage/client/sms/callback/AbstractMOServlet.java
src/main/java/com/vonage/client/sms/callback/messages/MO.java
src/main/java/com/vonage/client/sms/messages/Message.java
src/main/java/com/vonage/client/sms/messages/TextMessage.java
src/main/java/com/vonage/client/sms/messages/WapPushMessage.java
src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java
src/main/java/com/vonage/client/verify/BaseResult.java

Removed @author from the following files

---

src/main/java/com/vonage/client/application/Application.java
src/main/java/com/vonage/client/application/capabilities/Messages.java
src/main/java/com/vonage/client/application/capabilities/Rtc.java
src/main/java/com/vonage/client/application/capabilities/Voice.java

Removed unnecessary references to the "this" keyword for below models
- Messages.java
- Rtc.java
- Voice.java
- Application.java
Issue Link #305

Prasanna |  Removed unnecessary references to the "this" keyword

---

src/main/java/com/vonage/client/auth/TokenAuthMethod.java

Issue #305  
Removes unnecessary references to the "this" keyword in TokenAuthMethod.java

Remove unnecessary references to `this`

---

CONTRIBUTORS.md
src/main/java/com/vonage/client/verify/CheckEndpoint.java
src/main/java/com/vonage/client/verify/CheckResponse.java

Related Issue: https://github.com/Vonage/vonage-java-sdk/issues/305
Remove unnecessary usage of words from:
- from CheckEndpoint.java
- from CheckResponse.java

Remove unnecessary references to the "this" keyword.

---

README.md

Documented what APIs are currently supported in the SDK

API Support

---

.gitattributes
.github/workflows/build.yml
CONTRIBUTORS.md
src/test/java/com/vonage/client/VonageClientTest.java
src/test/java/com/vonage/client/voice/ncco/NccoTest.java

Some tests fail on Windows, mainly due to Windows linebreaks.
* [N/A] Updated [CHANGELOG.md](CHANGELOG.md)

Fix test failures on windows

---

src/test/java/com/vonage/client/sms/callback/AbstractMOServletTest.java

Hi , I added Calendar.NOVEMBER instead of 10 Magic constant

Added Calendar.NOVEMBER instead of 10 Magic constant

---

src/main/java/com/vonage/client/sms/SmsSubmissionResponseMessage.java
src/main/java/com/vonage/client/sns/request/SnsRequest.java
src/main/java/com/vonage/client/sns/response/SnsResponse.java
src/main/java/com/vonage/client/sns/response/SnsSubscribeResponse.java

Remove unnecessary this keyword from the following classes:
Fixes #305 
- SnsSubscribeResponse.java
- SnsResponse.java
- SnsRequest.java
- SmsSubmissionResponseMessage.java

Remove unnecessary reference of this keyword

---

README.md

Q&A for thread safety

---

.bumpversion.cfg
CHANGELOG.md
README.md
build.gradle
src/main/java/com/vonage/client/HttpWrapper.java

6.2.0 release

---

.github/workflows/build.yml
.github/workflows/release.yml
README.md
build.gradle
codecov.yml

moving to 6.x

---

.github/workflows/publish.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Automating release of the SDK to MavenCentral and refreshing the gradle file so that it's not outdated (lot's of deprecated stuff in there).

automating release and adding publish github action

---

CHANGELOG.md
src/main/java/com/vonage/client/voice/Call.java
src/test/java/com/vonage/client/voice/CallTest.java

adding random form number feature to VAPI

---

CHANGELOG.md
CONTRIBUTORS.md
src/main/java/com/vonage/client/incoming/CallEvent.java
src/test/java/com/vonage/client/incoming/CallEventTest.java

add call_uuid field for deserializing webhook response

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml
build.gradle
gradlew
gradlew.bat
src/main/java/com/vonage/client/HttpWrapper.java
src/main/java/com/vonage/client/voice/ncco/RecordAction.java
src/test/java/com/vonage/client/AbstractMethodTest.java
src/test/java/com/vonage/client/insight/AdvancedInsightResponseTest.java
src/test/java/com/vonage/client/voice/TalkPayloadTest.java

See https://jira.vonage.com/browse/DEVX-6104
This is a followup to #377 to address some tech debt, this time around Continuous Integration / release automation.
It has been tested using [act](https://github.com/nektos/act)

Update GitHub Workflow scripts

---

src/main/java/com/vonage/client/voice/ncco/TalkAction.java
src/test/java/com/vonage/client/voice/ncco/TalkActionTest.java

Added Premium field to TalkAction

---

CHANGELOG.md
src/main/java/com/vonage/client/messages/package-info.java
src/main/java/com/vonage/client/voice/ncco/Action.java
src/main/java/com/vonage/client/voice/ncco/PayAction.java
src/main/java/com/vonage/client/voice/ncco/PaymentPrompt.java
src/main/java/com/vonage/client/voice/ncco/TalkAction.java
src/test/java/com/vonage/client/voice/CallTest.java
src/test/java/com/vonage/client/voice/ncco/InputActionTest.java
src/test/java/com/vonage/client/voice/ncco/PayActionTest.java

This PR adds the Pay action, as described in the [NCCO reference documentation](https://developer.vonage.com/voice/voice-api/ncco-reference#pay).

Support payments over the phone

---

src/main/java/com/vonage/client/messages/MessagesClient.java
src/main/java/com/vonage/client/messages/SendMessageEndpoint.java
src/test/java/com/vonage/client/messages/MessagesClientTest.java

This PR adds a convenient way to use the Messages API sandbox.

Added toggle for Messages Sandbox

---

src/main/java/com/vonage/client/video/SessionStream.java
src/main/java/com/vonage/client/video/SignalAllEndpoint.java
src/main/java/com/vonage/client/video/SignalEndpoint.java
src/main/java/com/vonage/client/video/SignalRequest.java
src/main/java/com/vonage/client/video/SignalRequestWrapper.java
src/main/java/com/vonage/client/video/VideoClient.java
src/test/java/com/vonage/client/video/GetStreamEndpointTest.java
src/test/java/com/vonage/client/video/GetStreamResponseTest.java
src/test/java/com/vonage/client/video/ListStreamsEndpointTest.java
src/test/java/com/vonage/client/video/SetStreamLayoutEndpointTest.java
src/test/java/com/vonage/client/video/SetStreamLayoutRequestTest.java
src/test/java/com/vonage/client/video/SignalAllEndpointTest.java
src/test/java/com/vonage/client/video/SignalEndpointTest.java
src/test/java/com/vonage/client/video/SignalRequestTest.java
src/test/java/com/vonage/client/video/VideoClientTest.java

Adds Signalling capabilities, as described in [the current spec](https://developer.vonage.com/api/video#signaling).

Implement Signalling endpoints

---

README.md
src/main/java/com/vonage/client/video/Archive.java
src/main/java/com/vonage/client/video/ArchiveLayout.java
src/main/java/com/vonage/client/video/ArchiveMode.java
src/main/java/com/vonage/client/video/ArchiveStatus.java
src/main/java/com/vonage/client/video/ArchiveStream.java
src/main/java/com/vonage/client/video/CreateArchiveRequest.java
src/main/java/com/vonage/client/video/CreateSessionEndpoint.java
src/main/java/com/vonage/client/video/CreateSessionRequest.java
src/main/java/com/vonage/client/video/CreateSessionResponse.java
src/main/java/com/vonage/client/video/MediaMode.java
src/main/java/com/vonage/client/video/MuteSessionRequest.java
src/main/java/com/vonage/client/video/ProjectEnvironment.java
src/main/java/com/vonage/client/video/ProjectStatus.java
src/main/java/com/vonage/client/video/ScreenLayoutType.java
src/main/java/com/vonage/client/video/SessionStream.java
src/main/java/com/vonage/client/video/SignalAllEndpoint.java
src/main/java/com/vonage/client/video/SignalEndpoint.java
src/main/java/com/vonage/client/video/SignalRequest.java
src/main/java/com/vonage/client/video/SignalRequestWrapper.java
src/main/java/com/vonage/client/video/VideoClient.java
src/main/java/com/vonage/client/video/package-info.java
src/test/java/com/vonage/client/ClientTest.java
src/test/java/com/vonage/client/VonageClientTest.java
src/test/java/com/vonage/client/video/CreateArchiveEndpointTest.java
src/test/java/com/vonage/client/video/CreateArchiveRequestTest.java
src/test/java/com/vonage/client/video/SetScreenLayoutTypeEndpointTest.java
src/test/java/com/vonage/client/video/SetScreenLayoutTypeRequestTest.java
src/test/java/com/vonage/client/video/VideoClientTest.java

This PR makes various miscellaneous improvements to the Video API (beta), mainly on the testing and documentation. It adds some code samples to the README and improves `VideoClientTest`.

Tidy up video docs, tests & API

---

.github/workflows/publish.yml

Attempt to fix branch protection rule misfiring.

Force push bumpversion commit

---

README.md
build.gradle

Update link to Javadocs
